version: "3.8"
services:
  postgres:
    image: "postgres:latest"
    restart: always
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=4y7sV96vA9wv46VR
    ports:
      - "5432:5432"
